# ============================================================
# Notebook: 02_Silver_Transformation
# Purpose : Read raw trade messages from Bronze Delta,
#           parse JSON, apply schema, clean data,
#           and write structured data into Silver Delta layer.
# ============================================================


# ------------------------------------------------------------
# Step 1 - Import Required Libraries
# ------------------------------------------------------------

from pyspark.sql.functions import (
    col,
    from_json,
    current_timestamp,
    to_timestamp
)

from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    DoubleType,
    IntegerType
)


# ------------------------------------------------------------
# Step 2 - Define Bronze and Silver Paths
# ------------------------------------------------------------

bronze_path = "abfss://trade-data@sttradelakedev.dfs.core.windows.net/bronze/trades"

silver_path = "abfss://trade-data@sttradelakedev.dfs.core.windows.net/silver/trades"

quarantine_path = "abfss://trade-data@sttradelakedev.dfs.core.windows.net/silver/quarantine/trades"

silver_checkpoint_path = "abfss://trade-data@sttradelakedev.dfs.core.windows.net/silver/checkpoints/trades"


# ------------------------------------------------------------
# Step 3 - Read Bronze Delta Data
# ------------------------------------------------------------

bronze_df = (
    spark.read
    .format("delta")
    .load(bronze_path)
)

display(bronze_df)


# ------------------------------------------------------------
# Step 4 - Define JSON Schema for Trade Message
# ------------------------------------------------------------
# This schema must match the JSON generated by Python producer.

trade_schema = StructType([
    StructField("trade_id", StringType(), True),
    StructField("symbol", StringType(), True),
    StructField("price", DoubleType(), True),
    StructField("quantity", IntegerType(), True),
    StructField("trade_time", StringType(), True)
])


# ------------------------------------------------------------
# Step 5 - Parse Raw JSON Message
# ------------------------------------------------------------

parsed_df = (
    bronze_df
    .withColumn(
        "parsed_message",
        from_json(col("raw_message"), trade_schema)
    )
)

display(parsed_df)


# ------------------------------------------------------------
# Step 6 - Flatten Parsed JSON into Columns
# ------------------------------------------------------------

silver_df = (
    parsed_df
    .select(
        col("parsed_message.trade_id").alias("trade_id"),
        col("parsed_message.symbol").alias("symbol"),
        col("parsed_message.price").alias("price"),
        col("parsed_message.quantity").alias("quantity"),
        to_timestamp(col("parsed_message.trade_time")).alias("trade_time"),
        col("eventhub_enqueued_time"),
        current_timestamp().alias("silver_processed_time")
    )
)

display(silver_df)


# ------------------------------------------------------------
# Step 7 - Apply Basic Data Quality Rules
# ------------------------------------------------------------
# Remove invalid records:
# - trade_id should not be null
# - symbol should not be null
# - price should be greater than 0
# - quantity should be greater than 0
# Good records go to Silver.
# Bad records go to Quarantine for investigation.

good_silver_df = (
    silver_df
    .filter(col("trade_id").isNotNull())
    .filter(col("symbol").isNotNull())
    .filter(col("price") > 0)
    .filter(col("quantity") > 0)
)

bad_records_df = (
    silver_df
    .filter(
        col("trade_id").isNull() |
        col("symbol").isNull() |
        (col("price") <= 0) |
        (col("quantity") <= 0)
    )
)

display(good_silver_df)
display(bad_records_df)


# ------------------------------------------------------------
# Step 8 - Write Clean Data to Silver Delta and Bad Data to Quarantine
# ------------------------------------------------------------

(
    good_silver_df
    .write
    .format("delta")
    .mode("overwrite")
    .save(silver_path)
)

(
    bad_records_df
    .write
    .format("delta")
    .mode("overwrite")
    .save(quarantine_path)
)


# ------------------------------------------------------------
# Step 9 - Verify Silver Delta Data
# ------------------------------------------------------------

silver_result_df = (
    spark.read
    .format("delta")
    .load(silver_path)
)

display(silver_result_df)